name: Validate EDL Files

trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.11"
    displayName: Set up Python

  - script: python validate_edl.py
    displayName: Validate EDL Files
